spring:
  profiles:
    active: local

spring.batch.job.names: ${job.name:NONE}
logging.level.org.springframework.batch: DEBUG

---
spring:
  profiles: local
  datasource:
    url: jdbc:jtds:sybase://129.100.254.242:4000/tip;charset=eucksc;prepareSQL=0;socketTimeout=30
    username: tip
    password: tipuse
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    hikari:
      connection-test-query: select 1
